-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Active Intelligence skill gems
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["Portal"] = {
	name = "Portal",
	baseTypeName = "Portal",
	color = 4,
	baseEffectiveness = 0,
	description = "Creates a portal to the current area's town.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Triggerable] = true, [SkillType.TotemCastsAlone] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2.5,
	baseFlags = {
		spell = true,
	},
	qualityStats = {
		Default = {
			{ "base_cast_speed_+%", 3 },
		},
	},
	stats = {
		"base_deal_no_damage",
	},
	levels = {
		[1] = { levelRequirement = 10, },
		[2] = { levelRequirement = 10, },
		[3] = { levelRequirement = 10, },
		[4] = { levelRequirement = 10, },
		[5] = { levelRequirement = 10, },
		[6] = { levelRequirement = 10, },
		[7] = { levelRequirement = 10, },
		[8] = { levelRequirement = 10, },
		[9] = { levelRequirement = 10, },
		[10] = { levelRequirement = 10, },
	},
}
skills["Convocation"] = {
	name = "Convocation",
	baseTypeName = "Convocation",
	color = 4,
	description = "Recalls all minions that are following you to your location, and grants them a temporary life regeneration effect.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Buff] = true, [SkillType.Duration] = true, [SkillType.Triggerable] = true, [SkillType.Minion] = true, [SkillType.Instant] = true, [SkillType.Cooldown] = true, },
	statDescriptionScope = "buff_skill_stat_descriptions",
	castTime = 0,
	statMap = {
		["base_life_regeneration_rate_per_minute"] = {
			mod("LifeRegen", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
			div = 60,
		},
	},
	baseFlags = {
		spell = true,
		duration = true,
	},
	baseMods = {
		skill("buffMinions", true),
		skill("buffNotPlayer", true),
	},
	qualityStats = {
		Default = {
			{ "skill_effect_duration_+%", 1 },
			{ "base_cooldown_speed_+%", 1 },
		},
	},
	constantStats = {
		{ "base_skill_effect_duration", 2000 },
		{ "life_regeneration_rate_per_minute_%", 120 },
	},
	stats = {
		"base_deal_no_damage",
	},
	levels = {
		[1] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[2] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[3] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[4] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[5] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[6] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[7] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[8] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[9] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
		[10] = { cooldown = 3, levelRequirement = 31, storedUses = 1, cost = { Mana = 6, }, },
	},
}
skills["DetonateMines"] = {
	name = "Detonate Mines",
	baseTypeName = "Detonate Mines",
	color = 4,
	description = "Detonates a Mine, starting a Detonation Sequence which will detonate other Mines around it.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Triggerable] = true, [SkillType.Instant] = true, [SkillType.Cooldown] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0,
	baseFlags = {
		spell = true,
	},
	qualityStats = {
		Default = {
			{ "mine_detonation_speed_+%", 1 },
		},
	},
	constantStats = {
		{ "display_mine_deontation_mechanics_detonation_speed_+%_final_per_sequence_mine", 10 },
	},
	stats = {
		"base_deal_no_damage",
	},
	levels = {
		[1] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[2] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[3] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[4] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[5] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[6] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[7] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[8] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[9] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
		[10] = { cooldown = 0.2, levelRequirement = 8, storedUses = 1, },
	},
}